### ISSUE TITLE
[REQUIRED] Add/Delete/Find support for floating tasks

### ISSUE THREAD

**Issue by Skaty** [CS2103AUG2016-T14-C4/main#4]
# User Story
- As a **user**, I need to **add** tasks with no starting and deadline, so that I can keep track of general, non-time based tasks (such as buying milk).
- As a **user**, I need to **find** tasks in my todo list, so that I can access a certain task in my todo list.
- As a **user**, I need to **delete** tasks in my todo list, so that I can remove tasks that I do not have to take any further action on.
# TODO
- [x] Create command to add floating task. Format:  add TASK_NAME
- [x] Create command to find task. Format: find TASK_NAME
- [x] Create command to delete task. Format: delete ID

**Comment by AHaliq** [comment]
im working on add

**Comment by Skaty** [comment]
Twinned with #5.

**Comment by Skaty** [comment]
PR opened and merged: #6.
