### ISSUE TITLE
[REQUIRED] Refactor UI to fit Task App

### ISSUE THREAD

**Issue by Skaty** [CS2103AUG2016-T14-C4/main#5]
# TODO
- [x] Ensure that UI adheres to sample provided.
- [x] Ensure that UI is able to interact with underlying Task logic.
- [x] Automated UI testing (Optional)
# References
- Pull Request: #6

**Comment by Skaty** [comment]
PR merged.
